version: "2"

services:
  my-app:
    build: .
    ports:
     - 3000:3000
    container_name: my-app
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT:3000
      - MONGO_URI:mongodb://mongo:27017/test

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - './db:/data/db'
    